-- Velocube Support Panel - v3 upgrade
-- Run once in the velocube project: Dashboard -> SQL Editor -> New query.
-- Adds: delete permissions, agent management from the panel, and a guides
-- table so staff can edit help guides without touching code.
-- Safe to re-run.

-- ===================== New policies =====================

drop policy if exists "agents insert agents" on agents;
create policy "agents insert agents" on agents for insert to authenticated with check (true);
drop policy if exists "agents update agents" on agents;
create policy "agents update agents" on agents for update to authenticated using (true);

drop policy if exists "agents delete services" on services;
create policy "agents delete services" on services for delete to authenticated using (true);

drop policy if exists "agents delete clients" on clients;
create policy "agents delete clients" on clients for delete to authenticated using (true);

drop policy if exists "agents delete tickets" on tickets;
create policy "agents delete tickets" on tickets for delete to authenticated using (true);

drop policy if exists "agents delete messages" on ticket_messages;
create policy "agents delete messages" on ticket_messages for delete to authenticated using (true);

-- ===================== Guides table =====================

create table if not exists guides (
  id bigint generated by default as identity primary key,
  category text not null default 'General',
  title text not null unique,
  summary text not null default '',
  steps jsonb not null default '[]'::jsonb,
  sort int not null default 0
);

alter table guides enable row level security;
drop policy if exists "agents read guides" on guides;
drop policy if exists "agents insert guides" on guides;
drop policy if exists "agents update guides" on guides;
drop policy if exists "agents delete guides" on guides;
create policy "agents read guides" on guides for select to authenticated using (true);
create policy "agents insert guides" on guides for insert to authenticated with check (true);
create policy "agents update guides" on guides for update to authenticated using (true);
create policy "agents delete guides" on guides for delete to authenticated using (true);

-- ===================== Seed guides =====================

insert into guides (category, title, summary, steps, sort) values
('Plans & Billing', 'Explaining the three hosting plans', 'How to describe Self-Managed, Managed, and Website Management so clients pick the right one.', '["Ask one question first: do you want to make changes yourself, or send them to us?", "Self-Managed Hosting ($25/mo, 1 GB): we host and secure the site, the client edits everything from their client panel. Best for hands-on owners.", "Managed Hosting ($150/mo, 5 GB): the client emails any change request and we make it. No panel to learn. Best for busy owners.", "Website Management ($200/mo, 10 GB): everything in Managed Hosting plus proactive updates, security monitoring, weekly SEO and analytics reports, priority support, and discounted new work.", "All plans include SSL, daily backups, and 99.9% uptime monitoring. Never present one plan as worse, frame it as how hands-on they want to be."]'::jsonb, 1),
('Plans & Billing', 'Term discounts and how the math works', 'Quoting 3, 6, and 12 month terms correctly.', '["Discounts: 3 months saves 5%, 6 months saves 10%, 12 months saves 15%. They apply to hosting plans and monthly services, never to one-time project builds.", "Multiply the monthly price by the discount. Example: Managed Hosting at $150 on a 12 month term is $150 x 0.85 = $127.50/mo.", "Always quote the total saved too. Example: $22.50 x 12 = $270 saved over the year.", "The term starts on the next renewal date, not mid-cycle. Note the change in the account internal notes.", "Clients can upgrade plans mid-term and keep their discount. Downgrades take effect at the end of the term."]'::jsonb, 2),
('Plans & Billing', 'Handling a failed or late payment', 'What to do when a renewal payment does not go through.', '["Check the account status. Past due shows on the account header in this panel.", "Nothing is suspended automatically in the first 14 days. Reassure the client their site is safe.", "Send a friendly note through the ticket, never lead with consequences. Most failures are expired cards.", "If the client needs time, note the promised date in internal notes and set the ticket to pending.", "Past 14 days unpaid, escalate to an admin. Only admins pause hosting."]'::jsonb, 3),
('Hosting Support', 'Walking a client through the client panel', 'The five things Self-Managed clients ask about most.', '["Login: clients sign in at their panel link from their welcome email. Password resets are self-service from the login screen.", "Editing text: Content, then Pages, click any section, edit, then Publish. Changes are live in about a minute.", "Photos: Content, then Gallery, then Upload. Images compress automatically, no resizing needed.", "Business hours and contact info: Settings, then Business Info. This updates the site footer and contact page together.", "If they seem overwhelmed, mention Managed Hosting: for $150/mo they can just email us changes instead."]'::jsonb, 4),
('Hosting Support', 'Managed Hosting change requests by email', 'How the email change flow works and what to promise.', '["Managed and Website Management clients send changes to hr@velocube.net or reply to any ticket.", "Log every request as a ticket linked to their account, even small ones.", "Standard turnaround: same business day for text and image swaps, 2 to 3 days for new sections or layout changes.", "Anything that needs new development (a form, a feature, a new page type) gets quoted first. Create the quote request and tell the client the price before work starts.", "Confirm completion in the ticket with a link to the changed page."]'::jsonb, 5),
('Hosting Support', 'Storage limits and upgrades', 'What counts toward storage and how to sell more of it.', '["Limits: Self-Managed 1 GB, Managed 5 GB, Website Management 10 GB. Usage shows on the account page in this panel.", "Images, uploaded files, and backups count. The site code itself does not.", "Extra storage is $5 per GB per month, added to any plan.", "At 90% usage, reach out proactively before the client hits the wall.", "Large video files are usually the culprit. Offer to move video to a video host and embed it, which is often better than buying storage."]'::jsonb, 6),
('Tickets & Quotes', 'Handling a quote form lead', 'Turning a Get a Quote submission into a client.', '["Quote form submissions arrive as tickets with source quote form. Respond within 24 hours, that is a public promise on the website.", "Read what they asked for and match it to a tier: Single Page $250+, Business Website $900+, Advanced Build $2,200+, Online Store $3,800+, Complete Platform $6,500+, SEO Bundle $2,400+.", "Always offer hosting with the build. A Business Website plus Managed Hosting is our most common bundle.", "If the request is vague, reply with two or three specific questions rather than a generic price range.", "Once they accept, an admin creates the account and the project enters the services list."]'::jsonb, 7),
('Tickets & Quotes', 'Refunds and cancellations', 'What support can promise and what needs an admin.', '["Hosting and monthly plans: clients can cancel anytime, effective at the end of the paid period. No partial-month refunds.", "Term commitments: cancelling early forfeits the discount on the months already used. An admin calculates the adjustment.", "Project builds: the deposit is non-refundable once work starts. Remaining milestones are only billed as delivered.", "Never promise a refund amount in writing. Say you will confirm the exact figure and escalate to an admin the same day.", "Always ask why they are leaving and log it in the ticket. Retention offers (a free month, a plan downgrade) are admin approved."]'::jsonb, 8),
('Escalation', 'When to escalate to developers', 'Support fixes vs dev fixes, and how to hand off cleanly.', '["Escalate immediately: site fully down, checkout or booking broken, security warnings, data loss. Mark the ticket urgent.", "Escalate same day: broken forms, layout glitches on real devices, email delivery failures.", "Do not escalate: content changes, plan questions, billing, anything covered by a guide here.", "A good handoff includes: the account number, exact steps to reproduce, a screenshot or the client description, and what you already checked.", "Tell the client a human is on it and give a realistic window. Under-promise, over-deliver."]'::jsonb, 9)
on conflict (title) do nothing;
