-- Velocube Support Panel - full setup (v1 + v2 combined)
-- Run this ONCE in a fresh Supabase project: Dashboard -> SQL Editor -> New
-- query. Select all and delete anything already in the editor, paste this
-- entire file, and run it as a single execution.
-- Safe to re-run if it fails partway through.

-- ============================ Tables ============================

create table if not exists clients (
  id bigint generated by default as identity primary key,
  account_number text unique not null,
  business text not null,
  contact text not null,
  email text not null,
  phone text,
  plan text not null default 'None',
  monthly numeric not null default 0,
  term text default 'Monthly',
  storage_used numeric not null default 0,
  storage_limit numeric not null default 0,
  client_since date default now(),
  renewal_date date,
  status text not null default 'active',
  notes text default ''
);

create table if not exists services (
  id bigint generated by default as identity primary key,
  client_id bigint references clients (id) on delete cascade,
  name text not null,
  type text not null default 'project',
  price numeric not null default 0,
  status text not null default 'scheduled',
  progress int,
  started date,
  delivered date
);

create table if not exists tickets (
  id text primary key,
  client_id bigint references clients (id) on delete cascade,
  subject text not null,
  status text not null default 'open',
  priority text not null default 'normal',
  source text not null default 'email',
  assignee text default 'Unassigned',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists ticket_messages (
  id bigint generated by default as identity primary key,
  ticket_id text references tickets (id) on delete cascade,
  author text not null,
  direction text not null default 'outbound',
  body text not null,
  sent_at timestamptz not null default now()
);

-- v2 columns
alter table tickets add column if not exists tags text not null default '';
alter table ticket_messages add column if not exists internal boolean not null default false;
alter table ticket_messages add column if not exists email_status text;

create table if not exists agents (
  id bigint generated by default as identity primary key,
  name text not null,
  email text unique not null,
  role text not null default 'Support Agent',
  active boolean not null default true
);

create table if not exists canned_responses (
  id bigint generated by default as identity primary key,
  title text not null unique,
  category text not null default 'General',
  body text not null,
  created_at timestamptz not null default now()
);

create table if not exists activity (
  id bigint generated by default as identity primary key,
  ts timestamptz not null default now(),
  agent text not null,
  kind text not null,
  ref text not null default '',
  detail text not null default ''
);

-- ==================== Row Level Security ====================
-- Any signed-in user (an agent) can read and write. Agent accounts are
-- created only by admins in the Supabase Dashboard (Authentication ->
-- Users -> Add user), which enforces "only admins create accounts" until
-- the admin panel exists.

alter table clients enable row level security;
alter table services enable row level security;
alter table tickets enable row level security;
alter table ticket_messages enable row level security;
alter table agents enable row level security;
alter table canned_responses enable row level security;
alter table activity enable row level security;

drop policy if exists "agents read clients" on clients;
drop policy if exists "agents write clients" on clients;
drop policy if exists "agents insert clients" on clients;
create policy "agents read clients" on clients for select to authenticated using (true);
create policy "agents write clients" on clients for update to authenticated using (true);
create policy "agents insert clients" on clients for insert to authenticated with check (true);

drop policy if exists "agents read services" on services;
drop policy if exists "agents insert services" on services;
drop policy if exists "agents update services" on services;
create policy "agents read services" on services for select to authenticated using (true);
create policy "agents insert services" on services for insert to authenticated with check (true);
create policy "agents update services" on services for update to authenticated using (true);

drop policy if exists "agents read tickets" on tickets;
drop policy if exists "agents insert tickets" on tickets;
drop policy if exists "agents update tickets" on tickets;
create policy "agents read tickets" on tickets for select to authenticated using (true);
create policy "agents insert tickets" on tickets for insert to authenticated with check (true);
create policy "agents update tickets" on tickets for update to authenticated using (true);

drop policy if exists "agents read messages" on ticket_messages;
drop policy if exists "agents insert messages" on ticket_messages;
drop policy if exists "agents update messages" on ticket_messages;
create policy "agents read messages" on ticket_messages for select to authenticated using (true);
create policy "agents insert messages" on ticket_messages for insert to authenticated with check (true);
create policy "agents update messages" on ticket_messages for update to authenticated using (true);

drop policy if exists "agents read agents" on agents;
create policy "agents read agents" on agents for select to authenticated using (true);

drop policy if exists "agents read snippets" on canned_responses;
drop policy if exists "agents insert snippets" on canned_responses;
drop policy if exists "agents update snippets" on canned_responses;
drop policy if exists "agents delete snippets" on canned_responses;
create policy "agents read snippets" on canned_responses for select to authenticated using (true);
create policy "agents insert snippets" on canned_responses for insert to authenticated with check (true);
create policy "agents update snippets" on canned_responses for update to authenticated using (true);
create policy "agents delete snippets" on canned_responses for delete to authenticated using (true);

drop policy if exists "agents read activity" on activity;
drop policy if exists "agents insert activity" on activity;
create policy "agents read activity" on activity for select to authenticated using (true);
create policy "agents insert activity" on activity for insert to authenticated with check (true);

-- ============================ Seed ============================

insert into clients (account_number, business, contact, email, phone, plan, monthly, term, storage_used, storage_limit, client_since, renewal_date, status, notes) values
('VC-10001', 'East Village Buyers', 'Marcus Reid', 'marcus@eastvillagebuyers.com', '(212) 555-0134', 'Managed Hosting', 150, '12 months, 15% off', 2.1, 5, '2025-03-12', '2026-08-01', 'active', 'Prefers phone calls over email.'),
('VC-10002', 'Frontline Jerk', 'Alicia Thompson', 'alicia@frontlinejerk.com', '(718) 555-0187', 'Website Management', 200, '6 months, 10% off', 6.4, 10, '2025-01-20', '2026-09-15', 'active', 'Menu changes come in most Mondays.'),
('VC-10003', 'BoUnit NYC', 'Devon Carter', 'devon@bounitnyc.com', '(917) 555-0142', 'Self-Managed Hosting', 25, 'Monthly', 0.7, 1, '2025-06-02', '2026-08-02', 'active', 'Comfortable in the client panel.')
on conflict (account_number) do nothing;

insert into services (client_id, name, type, price, status, progress, started, delivered) values
(1, 'Business Website', 'project', 900, 'completed', 100, '2025-03-14', '2025-04-02'),
(1, 'Managed Hosting', 'subscription', 150, 'active', null, '2025-04-02', null),
(2, 'Online Store', 'project', 3800, 'completed', 100, '2025-01-22', '2025-03-15'),
(2, 'Website Management', 'subscription', 200, 'active', null, '2025-03-15', null),
(3, 'Online Store Build', 'project', 3800, 'in_progress', 35, '2026-06-20', null);

insert into tickets (id, client_id, subject, status, priority, source, assignee) values
('TK-2401', 2, 'Update Monday menu and add catering page', 'open', 'normal', 'email', 'Unassigned'),
('TK-2402', 3, 'How do I add product photos in the client panel?', 'resolved', 'low', 'email', 'Unassigned')
on conflict (id) do nothing;

insert into ticket_messages (ticket_id, author, direction, body, sent_at) values
('TK-2401', 'Alicia Thompson', 'inbound', 'Hi team. New menu attached for Monday. Also, we are launching catering next month. Can we get a catering page added with a request form?', now() - interval '1 day'),
('TK-2402', 'Devon Carter', 'inbound', 'Trying to add photos for the new drop but not sure where they go in the panel.', now() - interval '3 days');

insert into canned_responses (title, category, body) values
  ('Acknowledge + investigating', 'General',
   'Hi {name},' || chr(10) || chr(10) || 'Thanks for reaching out - we''ve received your request and are looking into it now. I''ll follow up shortly with an update.' || chr(10) || chr(10) || 'Best,' || chr(10) || '{agent}' || chr(10) || 'Velocube Support'),
  ('Change request received', 'Managed Hosting',
   'Hi {name},' || chr(10) || chr(10) || 'Got it - your change request is logged and in the queue. Text and image updates are usually live the same business day; new sections take 2-3 days. I''ll confirm here with a link once it''s done.' || chr(10) || chr(10) || 'Best,' || chr(10) || '{agent}' || chr(10) || 'Velocube Support'),
  ('Payment failed - friendly nudge', 'Billing',
   'Hi {name},' || chr(10) || chr(10) || 'A quick heads up: your latest renewal payment didn''t go through. No rush and nothing is suspended - most of the time it''s just an expired card. Reply here or call us when you''d like us to run it again.' || chr(10) || chr(10) || 'Best,' || chr(10) || '{agent}' || chr(10) || 'Velocube Support'),
  ('Quote follow-up', 'Sales',
   'Hi {name},' || chr(10) || chr(10) || 'Thanks for your interest in Velocube! To give you an exact quote I have a couple of quick questions:' || chr(10) || chr(10) || '1. ' || chr(10) || '2. ' || chr(10) || chr(10) || 'Once I hear back, you''ll have a firm number within 24 hours.' || chr(10) || chr(10) || 'Best,' || chr(10) || '{agent}' || chr(10) || 'Velocube Support'),
  ('Resolved + closing', 'General',
   'Hi {name},' || chr(10) || chr(10) || 'This is done - everything should be working on your end now. I''m marking the ticket resolved, but just reply here if anything else comes up and it will reopen automatically.' || chr(10) || chr(10) || 'Best,' || chr(10) || '{agent}' || chr(10) || 'Velocube Support'),
  ('Storage options', 'Hosting',
   'Hi {name},' || chr(10) || chr(10) || 'You''re getting close to your storage limit. Two options:' || chr(10) || chr(10) || '* Extra storage at $5 per GB per month, added to your current plan' || chr(10) || '* We move large video files to a video host and embed them, which usually frees most of your space' || chr(10) || chr(10) || 'Happy to walk through either - just let me know.' || chr(10) || chr(10) || 'Best,' || chr(10) || '{agent}' || chr(10) || 'Velocube Support')
on conflict (title) do nothing;
