-- Velocube Support Panel — v2 upgrade
-- Run AFTER supabase-setup.sql, once, in: Dashboard -> SQL Editor -> New query.
-- Adds: agents roster, canned responses, activity log, ticket tags,
-- internal notes, and email delivery tracking. Safe to re-run.

-- ===================== New columns =====================

alter table tickets add column if not exists tags text not null default '';
alter table ticket_messages add column if not exists internal boolean not null default false;
-- 'queued' | 'sent' | 'failed' | null (inbound / internal notes have null)
alter table ticket_messages add column if not exists email_status text;

-- ===================== Agents roster =====================
-- The assignee dropdown reads from here. Add one row per staff member.
-- (Auth accounts are still created in Authentication -> Users; this table
-- is just the display roster.)

create table if not exists agents (
  id bigint generated by default as identity primary key,
  name text not null,
  email text unique not null,
  role text not null default 'Support Agent',
  active boolean not null default true
);

alter table agents enable row level security;
drop policy if exists "agents read agents" on agents;
create policy "agents read agents" on agents for select to authenticated using (true);

-- ===================== Canned responses =====================

create table if not exists canned_responses (
  id bigint generated by default as identity primary key,
  title text not null unique,
  category text not null default 'General',
  body text not null,
  created_at timestamptz not null default now()
);

alter table canned_responses enable row level security;
drop policy if exists "agents read snippets" on canned_responses;
drop policy if exists "agents insert snippets" on canned_responses;
drop policy if exists "agents update snippets" on canned_responses;
drop policy if exists "agents delete snippets" on canned_responses;
create policy "agents read snippets" on canned_responses for select to authenticated using (true);
create policy "agents insert snippets" on canned_responses for insert to authenticated with check (true);
create policy "agents update snippets" on canned_responses for update to authenticated using (true);
create policy "agents delete snippets" on canned_responses for delete to authenticated using (true);

-- ===================== Activity log =====================

create table if not exists activity (
  id bigint generated by default as identity primary key,
  ts timestamptz not null default now(),
  agent text not null,
  kind text not null,          -- e.g. 'ticket_created', 'reply_sent', 'status_changed'
  ref text not null default '',-- e.g. 'TK-2401' or 'VC-10004'
  detail text not null default ''
);

alter table activity enable row level security;
drop policy if exists "agents read activity" on activity;
drop policy if exists "agents insert activity" on activity;
create policy "agents read activity" on activity for select to authenticated using (true);
create policy "agents insert activity" on activity for insert to authenticated with check (true);

-- ===================== Missing client + message policies =====================
-- v1 allowed reading/updating clients but not creating them from the panel.

drop policy if exists "agents insert clients" on clients;
create policy "agents insert clients" on clients for insert to authenticated with check (true);

drop policy if exists "agents update messages" on ticket_messages;
create policy "agents update messages" on ticket_messages for update to authenticated using (true);

drop policy if exists "agents insert services" on services;
create policy "agents insert services" on services for insert to authenticated with check (true);
drop policy if exists "agents update services" on services;
create policy "agents update services" on services for update to authenticated using (true);

-- ===================== Starter canned responses =====================

insert into canned_responses (title, category, body) values
  ('Acknowledge + investigating', 'General',
   'Hi {name},' || chr(10) || chr(10) || 'Thanks for reaching out — we''ve received your request and are looking into it now. I''ll follow up shortly with an update.' || chr(10) || chr(10) || 'Best,' || chr(10) || '{agent}' || chr(10) || 'Velocube Support'),
  ('Change request received', 'Managed Hosting',
   'Hi {name},' || chr(10) || chr(10) || 'Got it — your change request is logged and in the queue. Text and image updates are usually live the same business day; new sections take 2–3 days. I''ll confirm here with a link once it''s done.' || chr(10) || chr(10) || 'Best,' || chr(10) || '{agent}' || chr(10) || 'Velocube Support'),
  ('Payment failed — friendly nudge', 'Billing',
   'Hi {name},' || chr(10) || chr(10) || 'A quick heads up: your latest renewal payment didn''t go through. No rush and nothing is suspended — most of the time it''s just an expired card. Reply here or call us when you''d like us to run it again.' || chr(10) || chr(10) || 'Best,' || chr(10) || '{agent}' || chr(10) || 'Velocube Support'),
  ('Quote follow-up', 'Sales',
   'Hi {name},' || chr(10) || chr(10) || 'Thanks for your interest in Velocube! To give you an exact quote I have a couple of quick questions:' || chr(10) || chr(10) || '1. ' || chr(10) || '2. ' || chr(10) || chr(10) || 'Once I hear back, you''ll have a firm number within 24 hours.' || chr(10) || chr(10) || 'Best,' || chr(10) || '{agent}' || chr(10) || 'Velocube Support'),
  ('Resolved + closing', 'General',
   'Hi {name},' || chr(10) || chr(10) || 'This is done — everything should be working on your end now. I''m marking the ticket resolved, but just reply here if anything else comes up and it will reopen automatically.' || chr(10) || chr(10) || 'Best,' || chr(10) || '{agent}' || chr(10) || 'Velocube Support'),
  ('Storage options', 'Hosting',
   'Hi {name},' || chr(10) || chr(10) || 'You''re getting close to your storage limit. Two options:' || chr(10) || chr(10) || '• Extra storage at $5 per GB per month, added to your current plan' || chr(10) || '• We move large video files to a video host and embed them, which usually frees most of your space' || chr(10) || chr(10) || 'Happy to walk through either — just let me know.' || chr(10) || chr(10) || 'Best,' || chr(10) || '{agent}' || chr(10) || 'Velocube Support')
on conflict (title) do nothing;
