-- Velocube Support Panel — Supabase setup
-- Run this once in your Supabase project: Dashboard -> SQL Editor -> New query.
-- It creates the tables, locks them down so only signed-in agents can use
-- them, and seeds a small starter dataset.

-- ============================ Tables ============================

create table if not exists clients (
  id bigint generated by default as identity primary key,
  account_number text unique not null,
  business text not null,
  contact text not null,
  email text not null,
  phone text,
  plan text not null default 'None',
  monthly numeric not null default 0,
  term text default 'Monthly',
  storage_used numeric not null default 0,
  storage_limit numeric not null default 0,
  client_since date default now(),
  renewal_date date,
  status text not null default 'active',
  notes text default ''
);

create table if not exists services (
  id bigint generated by default as identity primary key,
  client_id bigint references clients (id) on delete cascade,
  name text not null,
  type text not null default 'project',
  price numeric not null default 0,
  status text not null default 'scheduled',
  progress int,
  started date,
  delivered date
);

create table if not exists tickets (
  id text primary key,
  client_id bigint references clients (id) on delete cascade,
  subject text not null,
  status text not null default 'open',
  priority text not null default 'normal',
  source text not null default 'email',
  assignee text default 'Unassigned',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists ticket_messages (
  id bigint generated by default as identity primary key,
  ticket_id text references tickets (id) on delete cascade,
  author text not null,
  direction text not null default 'outbound',
  body text not null,
  sent_at timestamptz not null default now()
);

-- ==================== Row Level Security ====================
-- Any signed-in user (an agent) can read and write. Agent accounts are
-- created only by admins in the Supabase Dashboard (Authentication ->
-- Users -> Add user), which enforces "only admins create accounts" until
-- the admin panel exists.

alter table clients enable row level security;
alter table services enable row level security;
alter table tickets enable row level security;
alter table ticket_messages enable row level security;

create policy "agents read clients" on clients for select to authenticated using (true);
create policy "agents write clients" on clients for update to authenticated using (true);
create policy "agents read services" on services for select to authenticated using (true);
create policy "agents read tickets" on tickets for select to authenticated using (true);
create policy "agents insert tickets" on tickets for insert to authenticated with check (true);
create policy "agents update tickets" on tickets for update to authenticated using (true);
create policy "agents read messages" on ticket_messages for select to authenticated using (true);
create policy "agents insert messages" on ticket_messages for insert to authenticated with check (true);

-- ============================ Seed ============================

insert into clients (account_number, business, contact, email, phone, plan, monthly, term, storage_used, storage_limit, client_since, renewal_date, status, notes) values
('VC-10001', 'East Village Buyers', 'Marcus Reid', 'marcus@eastvillagebuyers.com', '(212) 555-0134', 'Managed Hosting', 150, '12 months, 15% off', 2.1, 5, '2025-03-12', '2026-08-01', 'active', 'Prefers phone calls over email.'),
('VC-10002', 'Frontline Jerk', 'Alicia Thompson', 'alicia@frontlinejerk.com', '(718) 555-0187', 'Website Management', 200, '6 months, 10% off', 6.4, 10, '2025-01-20', '2026-09-15', 'active', 'Menu changes come in most Mondays.'),
('VC-10003', 'BoUnit NYC', 'Devon Carter', 'devon@bounitnyc.com', '(917) 555-0142', 'Self-Managed Hosting', 25, 'Monthly', 0.7, 1, '2025-06-02', '2026-08-02', 'active', 'Comfortable in the client panel.')
on conflict (account_number) do nothing;

insert into services (client_id, name, type, price, status, progress, started, delivered) values
(1, 'Business Website', 'project', 900, 'completed', 100, '2025-03-14', '2025-04-02'),
(1, 'Managed Hosting', 'subscription', 150, 'active', null, '2025-04-02', null),
(2, 'Online Store', 'project', 3800, 'completed', 100, '2025-01-22', '2025-03-15'),
(2, 'Website Management', 'subscription', 200, 'active', null, '2025-03-15', null),
(3, 'Online Store Build', 'project', 3800, 'in_progress', 35, '2026-06-20', null);

insert into tickets (id, client_id, subject, status, priority, source, assignee) values
('TK-2401', 2, 'Update Monday menu and add catering page', 'open', 'normal', 'email', 'Unassigned'),
('TK-2402', 3, 'How do I add product photos in the client panel?', 'resolved', 'low', 'email', 'Unassigned')
on conflict (id) do nothing;

insert into ticket_messages (ticket_id, author, direction, body, sent_at) values
('TK-2401', 'Alicia Thompson', 'inbound', 'Hi team. New menu attached for Monday. Also, we are launching catering next month. Can we get a catering page added with a request form?', now() - interval '1 day'),
('TK-2402', 'Devon Carter', 'inbound', 'Trying to add photos for the new drop but not sure where they go in the panel.', now() - interval '3 days');
