-- Velocube - Client Portal setup + security re-scoping
-- Run ONCE in the velocube project: Dashboard -> SQL Editor -> New query.
-- Run this AFTER supabase-clean-setup.sql and supabase-v3.sql.
-- Safe to re-run.
--
-- WHY THIS MATTERS
-- Until now every policy was "to authenticated using (true)", which was fine
-- because only staff had logins. Once clients can sign in to the same project,
-- that would let any client read every other client's data. This script
-- rewrites every policy so that:
--   * agents (email listed in the agents table) keep full access
--   * a client sees ONLY rows belonging to their own account
--   * internal staff notes never reach a client

-- ===================== Link auth users to clients =====================

alter table clients add column if not exists auth_user_id uuid references auth.users (id);
create unique index if not exists clients_auth_user_id_key on clients (auth_user_id);

-- ===================== Helper functions =====================
-- security definer so they can read the agents/clients tables without
-- triggering the very policies that call them (avoids infinite recursion).

create or replace function is_agent()
  returns boolean
  language sql
  security definer
  stable
  set search_path = public
as $$
  select exists (
    select 1 from agents
    where lower(email) = lower(auth.jwt() ->> 'email')
      and active
  );
$$;

create or replace function my_client_id()
  returns bigint
  language sql
  security definer
  stable
  set search_path = public
as $$
  select id from clients where auth_user_id = auth.uid() limit 1;
$$;

grant execute on function is_agent() to authenticated;
grant execute on function my_client_id() to authenticated;

-- ===================== New tables =====================

create table if not exists project_updates (
  id bigint generated by default as identity primary key,
  client_id bigint references clients (id) on delete cascade,
  title text not null,
  body text not null default '',
  kind text not null default 'progress',
  posted_by text not null default 'Velocube Team',
  created_at timestamptz not null default now()
);

create table if not exists documents (
  id bigint generated by default as identity primary key,
  client_id bigint references clients (id) on delete cascade,
  title text not null,
  kind text not null default 'agreement',
  body_md text not null default '',
  requires_signature boolean not null default false,
  signed_at timestamptz,
  signed_name text,
  signature_data text,
  signed_ip text,
  created_at timestamptz not null default now()
);

create table if not exists addon_orders (
  id bigint generated by default as identity primary key,
  client_id bigint references clients (id) on delete cascade,
  addon_key text not null,
  label text not null,
  price numeric not null default 0,
  status text not null default 'requested',
  note text default '',
  requested_at timestamptz not null default now()
);

create table if not exists announcements (
  id bigint generated by default as identity primary key,
  title text not null,
  body text not null default '',
  kind text not null default 'news',
  pinned boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists staging_sites (
  id bigint generated by default as identity primary key,
  client_id bigint references clients (id) on delete cascade,
  label text not null default 'Staging preview',
  url text not null,
  status text not null default 'live',
  last_deploy timestamptz not null default now()
);

alter table project_updates enable row level security;
alter table documents enable row level security;
alter table addon_orders enable row level security;
alter table announcements enable row level security;
alter table staging_sites enable row level security;

-- ===================== Safe client-facing view =====================
-- RLS is row-level, not column-level, so the portal reads the client
-- record through this view, which simply does not expose internal notes.

create or replace view client_self as
  select id, account_number, business, contact, email, phone, plan, monthly,
         term, storage_used, storage_limit, client_since, renewal_date, status
  from clients
  where auth_user_id = auth.uid();

grant select on client_self to authenticated;

-- ===================== Rewritten policies: clients =====================

drop policy if exists "agents read clients" on clients;
drop policy if exists "agents write clients" on clients;
drop policy if exists "agents insert clients" on clients;
drop policy if exists "agents delete clients" on clients;
drop policy if exists "scoped read clients" on clients;
drop policy if exists "scoped update clients" on clients;

create policy "scoped read clients" on clients for select to authenticated
  using (is_agent() or auth_user_id = auth.uid());
create policy "scoped update clients" on clients for update to authenticated
  using (is_agent() or auth_user_id = auth.uid());
create policy "agents insert clients" on clients for insert to authenticated
  with check (is_agent());
create policy "agents delete clients" on clients for delete to authenticated
  using (is_agent());

-- ===================== services =====================

drop policy if exists "agents read services" on services;
drop policy if exists "agents insert services" on services;
drop policy if exists "agents update services" on services;
drop policy if exists "agents delete services" on services;
drop policy if exists "scoped read services" on services;

create policy "scoped read services" on services for select to authenticated
  using (is_agent() or client_id = my_client_id());
create policy "agents insert services" on services for insert to authenticated
  with check (is_agent());
create policy "agents update services" on services for update to authenticated
  using (is_agent());
create policy "agents delete services" on services for delete to authenticated
  using (is_agent());

-- ===================== tickets =====================

drop policy if exists "agents read tickets" on tickets;
drop policy if exists "agents insert tickets" on tickets;
drop policy if exists "agents update tickets" on tickets;
drop policy if exists "agents delete tickets" on tickets;
drop policy if exists "scoped read tickets" on tickets;
drop policy if exists "scoped insert tickets" on tickets;

create policy "scoped read tickets" on tickets for select to authenticated
  using (is_agent() or client_id = my_client_id());
create policy "scoped insert tickets" on tickets for insert to authenticated
  with check (is_agent() or client_id = my_client_id());
create policy "agents update tickets" on tickets for update to authenticated
  using (is_agent());
create policy "agents delete tickets" on tickets for delete to authenticated
  using (is_agent());

-- ===================== ticket_messages =====================
-- Clients see only non-internal messages on their own tickets, and can
-- only ever insert non-internal ones.

drop policy if exists "agents read messages" on ticket_messages;
drop policy if exists "agents insert messages" on ticket_messages;
drop policy if exists "agents update messages" on ticket_messages;
drop policy if exists "agents delete messages" on ticket_messages;
drop policy if exists "scoped read messages" on ticket_messages;
drop policy if exists "scoped insert messages" on ticket_messages;

create policy "scoped read messages" on ticket_messages for select to authenticated
  using (
    is_agent()
    or (
      internal = false
      and exists (
        select 1 from tickets t
        where t.id = ticket_messages.ticket_id
          and t.client_id = my_client_id()
      )
    )
  );

create policy "scoped insert messages" on ticket_messages for insert to authenticated
  with check (
    is_agent()
    or (
      internal = false
      and exists (
        select 1 from tickets t
        where t.id = ticket_messages.ticket_id
          and t.client_id = my_client_id()
      )
    )
  );

create policy "agents update messages" on ticket_messages for update to authenticated
  using (is_agent());
create policy "agents delete messages" on ticket_messages for delete to authenticated
  using (is_agent());

-- ===================== Staff-only tables =====================
-- agents, canned_responses, activity, guides: agents only. The portal
-- never queries these.

drop policy if exists "agents read agents" on agents;
drop policy if exists "agents insert agents" on agents;
drop policy if exists "agents update agents" on agents;
create policy "agents read agents" on agents for select to authenticated using (is_agent());
create policy "agents insert agents" on agents for insert to authenticated with check (is_agent());
create policy "agents update agents" on agents for update to authenticated using (is_agent());

drop policy if exists "agents read snippets" on canned_responses;
drop policy if exists "agents insert snippets" on canned_responses;
drop policy if exists "agents update snippets" on canned_responses;
drop policy if exists "agents delete snippets" on canned_responses;
create policy "agents read snippets" on canned_responses for select to authenticated using (is_agent());
create policy "agents insert snippets" on canned_responses for insert to authenticated with check (is_agent());
create policy "agents update snippets" on canned_responses for update to authenticated using (is_agent());
create policy "agents delete snippets" on canned_responses for delete to authenticated using (is_agent());

drop policy if exists "agents read activity" on activity;
drop policy if exists "agents insert activity" on activity;
create policy "agents read activity" on activity for select to authenticated using (is_agent());
create policy "agents insert activity" on activity for insert to authenticated with check (is_agent());

drop policy if exists "agents read guides" on guides;
drop policy if exists "agents insert guides" on guides;
drop policy if exists "agents update guides" on guides;
drop policy if exists "agents delete guides" on guides;
create policy "agents read guides" on guides for select to authenticated using (is_agent());
create policy "agents insert guides" on guides for insert to authenticated with check (is_agent());
create policy "agents update guides" on guides for update to authenticated using (is_agent());
create policy "agents delete guides" on guides for delete to authenticated using (is_agent());

-- ===================== New table policies =====================

drop policy if exists "scoped read updates" on project_updates;
create policy "scoped read updates" on project_updates for select to authenticated
  using (is_agent() or client_id = my_client_id());
drop policy if exists "agents write updates" on project_updates;
create policy "agents write updates" on project_updates for insert to authenticated with check (is_agent());
drop policy if exists "agents update updates" on project_updates;
create policy "agents update updates" on project_updates for update to authenticated using (is_agent());
drop policy if exists "agents delete updates" on project_updates;
create policy "agents delete updates" on project_updates for delete to authenticated using (is_agent());

drop policy if exists "scoped read documents" on documents;
create policy "scoped read documents" on documents for select to authenticated
  using (is_agent() or client_id = my_client_id());
-- clients may sign (update) their own documents; agents may update anything
drop policy if exists "scoped update documents" on documents;
create policy "scoped update documents" on documents for update to authenticated
  using (is_agent() or client_id = my_client_id());
drop policy if exists "agents insert documents" on documents;
create policy "agents insert documents" on documents for insert to authenticated with check (is_agent());
drop policy if exists "agents delete documents" on documents;
create policy "agents delete documents" on documents for delete to authenticated using (is_agent());

drop policy if exists "scoped read addons" on addon_orders;
create policy "scoped read addons" on addon_orders for select to authenticated
  using (is_agent() or client_id = my_client_id());
drop policy if exists "scoped insert addons" on addon_orders;
create policy "scoped insert addons" on addon_orders for insert to authenticated
  with check (is_agent() or client_id = my_client_id());
drop policy if exists "agents update addons" on addon_orders;
create policy "agents update addons" on addon_orders for update to authenticated using (is_agent());
drop policy if exists "agents delete addons" on addon_orders;
create policy "agents delete addons" on addon_orders for delete to authenticated using (is_agent());

drop policy if exists "all read announcements" on announcements;
create policy "all read announcements" on announcements for select to authenticated using (true);
drop policy if exists "agents write announcements" on announcements;
create policy "agents write announcements" on announcements for insert to authenticated with check (is_agent());
drop policy if exists "agents update announcements" on announcements;
create policy "agents update announcements" on announcements for update to authenticated using (is_agent());
drop policy if exists "agents delete announcements" on announcements;
create policy "agents delete announcements" on announcements for delete to authenticated using (is_agent());

drop policy if exists "scoped read staging" on staging_sites;
create policy "scoped read staging" on staging_sites for select to authenticated
  using (is_agent() or client_id = my_client_id());
drop policy if exists "agents write staging" on staging_sites;
create policy "agents write staging" on staging_sites for insert to authenticated with check (is_agent());
drop policy if exists "agents update staging" on staging_sites;
create policy "agents update staging" on staging_sites for update to authenticated using (is_agent());
drop policy if exists "agents delete staging" on staging_sites;
create policy "agents delete staging" on staging_sites for delete to authenticated using (is_agent());

-- ===================== Grants =====================

grant usage on schema public to authenticated;
grant select, insert, update, delete on all tables in schema public to authenticated;
grant usage, select on all sequences in schema public to authenticated;

-- ===================== Starter announcements =====================

insert into announcements (title, body, kind, pinned) values
('Welcome to your Velocube portal', 'Track your project, message the team, review documents, and manage your plan from one place. Anything you need, send us a message and we will get back to you within one business day.', 'news', true),
('Support hours', 'Our team is available Monday to Friday, 9am to 6pm Eastern. Urgent hosting issues are monitored around the clock.', 'news', false)
on conflict do nothing;
